### ISSUE TITLE
SQLite error

### ISSUE THREAD

**Issue by Dima107** [distriqt/ANE-GooglePlayServices#12]
It's not crash. Just error messages into logcat.
Can you help me to understand where I can fine source of this problem? I see that it can be related to Google Services

2020-05-08 18:28:57.837 30489-14119/? E/SQLiteDatabase: Error inserting period=6996000 preferred_charging_state=1 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService required_network_type=0 runtime=1588951737830 required_idleness_state=0 source=16 service_kind=0 target_package=com.google.android.gms source_version=201216000 last_runtime=0 user_id=0 job_id=-1 requires_charging=0 tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG flex_time=3497000 task_type=0 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}}
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1564)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1433)
        at aqch.a(:com.google.android.gms@201216029@20.12.16 (100406-306753009):78)
        at aqbw.a(:com.google.android.gms@201216029@20.12.16 (100406-306753009):167)
        at aqbw.a(:com.google.android.gms@201216029@20.12.16 (100406-306753009):21)
        at aqbw.a(:com.google.android.gms@201216029@20.12.16 (100406-306753009):161)
        at apyg.run(:com.google.android.gms@201216029@20.12.16 (100406-306753009):8)
        at thp.b(:com.google.android.gms@201216029@20.12.16 (100406-306753009):12)
        at thp.run(:com.google.android.gms@201216029@20.12.16 (100406-306753009):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at tno.run(:com.google.android.gms@201216029@20.12.16 (100406-306753009):0)
        at java.lang.Thread.run(Thread.java:764)

air sdk 33.1.198. 
many your ANEs are in project: firebase, game services, facebook, aplication
Ironsource SDK 6.14.0 + adapters

**Comment by marchbold** [comment]
Probably related to Firebase, so I'll move this issue to the Firebase repository.
