### ISSUE TITLE
ANE Not Working Anymore for GameCenter & Play Services

### ISSUE THREAD

**Issue by Mennez** [distriqt/ANE-GooglePlayServices#18]
In the past few days I tried to implement the district ANE for Google Play Services and Game Center. I did do this before with a  different ANE for Play Services (see: [Old ANE Issue form freshplanet](https://github.com/freshplanet/ANE-Google-Play-Game-Services/issues/6)). However, since this is a newer, paid and more supported ANE, I wanted to use the one of distriqt.

I have set up Game Center and Play Services with all achievements, leaderboards, certificates, etc. correctly. I am going to share my XML code. I can't find any issue, but maybe someone else does? I tried both 'clashflash.justicekeepers' and 'air.clashflash.justicekeepers' for the ID, both no success:

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<application xmlns="http://ns.adobe.com/air/application/33.1">
    <id>clashflash.justicekeepers</id>
    <versionNumber>1.0.1</versionNumber>
    <filename>Justice Keepers</filename>
    <description></description>
    <name>Justice Keepers</name>
    <copyright></copyright>
    <initialWindow>
        <content>Justice%20Keepers.swf</content>
        <systemChrome>standard</systemChrome>
        <transparent>false</transparent>
        <visible>true</visible>
        <fullScreen>true</fullScreen>
        <autoOrients>false</autoOrients>
        <aspectRatio>landscape</aspectRatio>
        <renderMode>gpu</renderMode>
    </initialWindow>
    <customUpdateUI>false</customUpdateUI>
    <allowBrowserInvocation>false</allowBrowserInvocation>
    <icon>
        <image192x192>bin/icons/192x192.png</image192x192>
        <image144x144>bin/icons/144x144.png</image144x144>
        <image96x96>bin/icons/96x96.png</image96x96>
        <image72x72>bin/icons/72x72.png</image72x72>
        <image48x48>bin/icons/48x48.png</image48x48>
        <image36x36>bin/icons/36x36.png</image36x36>
    </icon>
    <android>
        <!-- 16bit of 32bit; 16bit kan de render prestaties verbeteren, maar
        dit gaat ten koste van de zogenaamde kleurgetrouwheid -->
        <colorDepth>32bit</colorDepth>
        <manifestAdditions><![CDATA[
            <manifest android:installLocation="auto">
                <uses-permission android:name="android.permission.INTERNET"/>
                <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
                <uses-permission android:name="android.permission.WAKE_LOCK"/>
                <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
                <application>
                    <meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ 544453475776" />
                    <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
                    <activity
                        android:name="com.google.android.gms.auth.api.signin.internal.SignInHubActivity"
                        android:excludeFromRecents="true"
                        android:exported="false"
                        android:theme="@android:style/Theme.Translucent.NoTitleBar" />
                    <service
                        android:name="com.google.android.gms.auth.api.signin.RevocationBoundService"
                        android:exported="true"
                        android:permission="com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION" />
                    <activity
                        android:name="com.google.android.gms.common.api.GoogleApiActivity"
                        android:exported="false"
                        android:theme="@android:style/Theme.Translucent.NoTitleBar" />
                </application>
            </manifest>
            ]]></manifestAdditions>
    </android>
    <supportedLanguages>en</supportedLanguages>
    <versionLabel></versionLabel>
    <iPhone>
        <requestedDisplayResolution>high</requestedDisplayResolution>
        <InfoAdditions><![CDATA[
            <key>UIDeviceFamily</key>
            <array><string>1</string><string>2</string></array>
        ]]></InfoAdditions>
    </iPhone>
    <extensions>
        <extensionID>com.amanitadesign.steam.FRESteamWorks</extensionID>
        <extensionID>com.distriqt.playservices.Games</extensionID>
        <extensionID>com.distriqt.playservices.Base</extensionID>
        <extensionID>com.distriqt.playservices.Ads</extensionID>
        <extensionID>com.distriqt.playservices.Drive</extensionID>
        <extensionID>com.distriqt.playservices.Auth</extensionID>
        <extensionID>com.distriqt.Core</extensionID>
        <extensionID>androidx.appcompat</extensionID>
        <extensionID>androidx.core</extensionID>
        <extensionID>com.distriqt.GameServices</extensionID>
    </extensions>
</application>
```

I already published the Google Play Services achievements and leaderboards (just to be sure). When I start the game on iOS, it runs fine. However Game Center is never initialised (no welcome back screen or what so ever). Here some screen shots of my Apple Connect setup:

![Screenshot 2020-12-10 at 11 25 40](https://user-images.githubusercontent.com/6833463/101760154-cc4fde80-3ada-11eb-8810-dea7be51209b.png)

![Screenshot 2020-12-10 at 11 26 06](https://user-images.githubusercontent.com/6833463/101760168-cfe36580-3ada-11eb-9482-5c55cd6378a0.png)

And some screen shots of my Google Play Services setup:

![all-my-apps-config](https://user-images.githubusercontent.com/6833463/101760223-e689bc80-3ada-11eb-82a2-8bde2f196156.png)

![config-play-services](https://user-images.githubusercontent.com/6833463/101760242-eb4e7080-3ada-11eb-88cf-a892e12afd19.png)

When I run the app on my Android device for testing, I get the login pop up for like 2-3 seconds, and then the event listener SIGN_IN_FAILED handler returns:

```
[Event type="signin:failed" bubbles=false cancelable=false eventPhase=2]
There was an issue with sign in.  Please try again later.
```

This issue is the same as I had 6 years before with the one from fresh planet. This was solved in my case by uploading a test APK to Google Play. I tried this as well now, but it didn't work out.

I really hope someone can help me out. I purchased a license for Apple and Distriqt to release the game with Game Center and Play Services for my game I was developing like 6 years (yeah really!), but this is getting pretty frustrating now since I can't finish the final step :-(...

Thanks a million for helping me (and maybe others) out!

**Comment by Mennez** [comment]
I've some more additional information from my Android device via add logcat:

```
12-10 13:16:13.233 12198 12198 D com.distriqt.GameServices: GameServicesManager::initialiseService( google:play:game:services )
12-10 13:16:13.237 12198 12198 D com.distriqt.GameServices: GooglePlayGameService::initialiseService(  )
12-10 13:16:13.862 12198 12198 D com.distriqt.GameServices: GameServicesManager::signIn()
12-10 13:16:13.862 12198 12198 D com.distriqt.GameServices: GooglePlayGameService::signIn( false )
12-10 13:16:13.863 12198 12198 D com.distriqt.GameServices: GooglePlayGameService::signIn(): currentAccount = 
12-10 13:16:13.863 12198 12198 D com.distriqt.GameServices: GooglePlayGameService::signIn(): STARTING NORMAL SIGN IN
12-10 13:16:13.879 12198 12198 D com.distriqt.GameServices: GooglePlayGameService::signIn(): getSignInIntent()
12-10 13:16:13.883 12198 12198 D com.distriqt.GameServices: GooglePlayGameService::signIn(): startActivityForResult( Intent { act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=air.clashflash.justicekeepers cmp=air.clashflash.justicekeepers/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (has extras) } )
12-10 13:16:14.213  2926  5772 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void j.j.gb(long)' on a null object reference
12-10 13:16:14.213  2926  5772 W System.err: 	at j.g.fv(:796)
12-10 13:16:14.213  2926  5772 W System.err: 	at j.b.ew(:1161)
12-10 13:16:14.213  2926  5772 W System.err: 	at com.android.server.ssrm.siop.ay.mE(:187)
12-10 13:16:14.213  2926  5772 W System.err: 	at com.android.server.ssrm.C.Gt(:1504)
12-10 13:16:14.213  2926  5772 W System.err: 	at com.android.server.ssrm.aI.handleMessage(:596)
12-10 13:16:14.213  2926  5772 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-10 13:16:14.213  2926  5772 W System.err: 	at android.os.Looper.loop(Looper.java:164)
12-10 13:16:14.213  2926  5772 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-10 13:16:14.436  2926  3113 W System.err: java.io.FileNotFoundException: /sys/class/mdnie/mdnie/scenario (No such file or directory)
12-10 13:16:14.436  2926  3113 W System.err: 	at java.io.FileInputStream.open0(Native Method)
12-10 13:16:14.436  2926  3113 W System.err: 	at java.io.FileInputStream.open(FileInputStream.java:200)
12-10 13:16:14.436  2926  3113 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
12-10 13:16:14.437  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService.getStringFromFile(MdnieScenarioControlService.java:1819)
12-10 13:16:14.437  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService.setUIMode(MdnieScenarioControlService.java:1172)
12-10 13:16:14.437  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService.-wrap14(Unknown Source:0)
12-10 13:16:14.437  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService$MSCSControlHandler.handleMessage(MdnieScenarioControlService.java:1142)
12-10 13:16:14.437  2926  3113 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-10 13:16:14.437  2926  3113 W System.err: 	at android.os.Looper.loop(Looper.java:164)
12-10 13:16:14.437  2926  3113 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-10 13:16:15.448  2926  5772 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void j.j.gb(long)' on a null object reference
12-10 13:16:15.448  2926  5772 W System.err: 	at j.g.fv(:796)
12-10 13:16:15.448  2926  5772 W System.err: 	at j.b.ew(:1161)
12-10 13:16:15.448  2926  5772 W System.err: 	at com.android.server.ssrm.siop.ay.mE(:187)
12-10 13:16:15.448  2926  5772 W System.err: 	at com.android.server.ssrm.C.Gt(:1504)
12-10 13:16:15.449  2926  5772 W System.err: 	at com.android.server.ssrm.aI.handleMessage(:596)
12-10 13:16:15.449  2926  5772 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-10 13:16:15.449  2926  5772 W System.err: 	at android.os.Looper.loop(Looper.java:164)
12-10 13:16:15.449  2926  5772 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-10 13:16:15.666  2926  3113 W System.err: java.io.FileNotFoundException: /sys/class/mdnie/mdnie/scenario (No such file or directory)
12-10 13:16:15.666  2926  3113 W System.err: 	at java.io.FileInputStream.open0(Native Method)
12-10 13:16:15.666  2926  3113 W System.err: 	at java.io.FileInputStream.open(FileInputStream.java:200)
12-10 13:16:15.666  2926  3113 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
12-10 13:16:15.666  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService.getStringFromFile(MdnieScenarioControlService.java:1819)
12-10 13:16:15.666  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService.setUIMode(MdnieScenarioControlService.java:1172)
12-10 13:16:15.666  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService.-wrap14(Unknown Source:0)
12-10 13:16:15.666  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService$MSCSControlHandler.handleMessage(MdnieScenarioControlService.java:1142)
12-10 13:16:15.666  2926  3113 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-10 13:16:15.666  2926  3113 W System.err: 	at android.os.Looper.loop(Looper.java:164)
12-10 13:16:15.666  2926  3113 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-10 13:16:20.477 12198 12198 D com.distriqt.GameServices: GooglePlayGameService::onActivityResult( 90001,  0, Bundle{
12-10 13:16:20.477 12198 12198 D com.distriqt.GameServices:  googleSignInStatus => Status{statusCode=SIGN_IN_REQUIRED, resolution=null};
12-10 13:16:20.477 12198 12198 D com.distriqt.GameServices:  }Bundle )
12-10 13:16:20.510  2926  3113 W System.err: java.io.FileNotFoundException: /sys/class/mdnie/mdnie/scenario (No such file or directory)
12-10 13:16:20.510  2926  3113 W System.err: 	at java.io.FileInputStream.open0(Native Method)
12-10 13:16:20.510  2926  3113 W System.err: 	at java.io.FileInputStream.open(FileInputStream.java:200)
12-10 13:16:20.510  2926  3113 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
12-10 13:16:20.510  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService.getStringFromFile(MdnieScenarioControlService.java:1819)
12-10 13:16:20.510  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService.setUIMode(MdnieScenarioControlService.java:1172)
12-10 13:16:20.510  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService.-wrap14(Unknown Source:0)
12-10 13:16:20.510  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService$MSCSControlHandler.handleMessage(MdnieScenarioControlService.java:1142)
12-10 13:16:20.510  2926  3113 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-10 13:16:20.510  2926  3113 W System.err: 	at android.os.Looper.loop(Looper.java:164)
12-10 13:16:20.510  2926  3113 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-10 13:16:20.640  2926  3113 W System.err: java.io.FileNotFoundException: /sys/class/mdnie/mdnie/scenario (No such file or directory)
12-10 13:16:20.641  2926  3113 W System.err: 	at java.io.FileInputStream.open0(Native Method)
12-10 13:16:20.641  2926  3113 W System.err: 	at java.io.FileInputStream.open(FileInputStream.java:200)
12-10 13:16:20.641  2926  3113 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
12-10 13:16:20.641  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService.getStringFromFile(MdnieScenarioControlService.java:1819)
12-10 13:16:20.641  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService.setUIMode(MdnieScenarioControlService.java:1172)
12-10 13:16:20.641  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService.-wrap14(Unknown Source:0)
12-10 13:16:20.641  2926  3113 W System.err: 	at com.samsung.android.displaysolution.MdnieScenarioControlService$MSCSControlHandler.handleMessage(MdnieScenarioControlService.java:1142)
12-10 13:16:20.641  2926  3113 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-10 13:16:20.641  2926  3113 W System.err: 	at android.os.Looper.loop(Looper.java:164)
12-10 13:16:20.641  2926  3113 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-10 13:16:20.718  2926  5772 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void j.j.gb(long)' on a null object reference
12-10 13:16:20.719  2926  5772 W System.err: 	at j.g.fv(:796)
12-10 13:16:20.719  2926  5772 W System.err: 	at j.b.ew(:1161)
12-10 13:16:20.719  2926  5772 W System.err: 	at com.android.server.ssrm.siop.ay.mE(:187)
12-10 13:16:20.719  2926  5772 W System.err: 	at com.android.server.ssrm.C.Gt(:1504)
12-10 13:16:20.719  2926  5772 W System.err: 	at com.android.server.ssrm.aI.handleMessage(:596)
12-10 13:16:20.719  2926  5772 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-10 13:16:20.719  2926  5772 W System.err: 	at android.os.Looper.loop(Looper.java:164)
12-10 13:16:20.719  2926  5772 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
```
